server:
  port: 8880

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/collectordb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect